import type { GiftCardRecord } from "@/src/components/dashboard/gift-cards/types";

export const MOCK_GIFT_CARDS: GiftCardRecord[] = [
  {
    id: "zg-1842",
    code: "ZG-1842",
    buyerName: "Anna L.",
    buyerEmail: "anna@email.ch",
    recipientName: "Paul L.",
    amountChf: 100,
    balanceChf: 36,
    type: "digital",
    status: "active",
    purchasedAt: "2026-08-25",
    purchasedLabel: "25 août 2026",
    expiresLabel: "25 août 2027",
    qrPlaceholder: "QR-ZG-1842",
    usageHistory: [
      {
        id: "u-1842-1",
        dateLabel: "25 août 2026",
        amountUsedChf: 64,
        remainingBalanceChf: 36,
      },
    ],
  },
  {
    id: "zg-1841",
    code: "ZG-1841",
    buyerName: "Marc D.",
    buyerEmail: "marc@email.ch",
    recipientName: null,
    amountChf: 150,
    balanceChf: 0,
    type: "paper",
    status: "used",
    purchasedAt: "2026-08-24",
    purchasedLabel: "24 août 2026",
    expiresLabel: "24 août 2027",
    qrPlaceholder: "QR-ZG-1841",
    usageHistory: [
      {
        id: "u-1841-1",
        dateLabel: "24 août 2026",
        amountUsedChf: 150,
        remainingBalanceChf: 0,
      },
    ],
  },
  {
    id: "zg-1840",
    code: "ZG-1840",
    buyerName: "Sophie R.",
    buyerEmail: "sophie@email.ch",
    recipientName: "Léa R.",
    amountChf: 50,
    balanceChf: 50,
    type: "digital",
    status: "active",
    purchasedAt: "2026-08-23",
    purchasedLabel: "23 août 2026",
    expiresLabel: "23 août 2027",
    qrPlaceholder: "QR-ZG-1840",
    usageHistory: [],
  },
  {
    id: "zg-1839",
    code: "ZG-1839",
    buyerName: "Thomas K.",
    buyerEmail: "thomas@email.ch",
    recipientName: null,
    amountChf: 80,
    balanceChf: 80,
    type: "paper",
    status: "expired",
    purchasedAt: "2025-08-10",
    purchasedLabel: "10 août 2025",
    expiresLabel: "10 août 2026",
    qrPlaceholder: "QR-ZG-1839",
    usageHistory: [],
  },
  {
    id: "zg-1838",
    code: "ZG-1838",
    buyerName: "Clara M.",
    buyerEmail: "clara@email.ch",
    recipientName: "Noah M.",
    amountChf: 200,
    balanceChf: 120,
    type: "digital",
    status: "disabled",
    purchasedAt: "2026-08-02",
    purchasedLabel: "2 août 2026",
    expiresLabel: "2 août 2027",
    qrPlaceholder: "QR-ZG-1838",
    usageHistory: [
      {
        id: "u-1838-1",
        dateLabel: "12 août 2026",
        amountUsedChf: 80,
        remainingBalanceChf: 120,
      },
    ],
  },
];

export function formatChf(amount: number): string {
  return `${amount.toLocaleString("fr-CH")}\u00a0CHF`;
}
